ACTIVITIES = [
    ("sunbathing", "Tomar el sol", "/static/icons/tomar_sol.png"),
    ("surf", "Surf", "/static/icons/surf.png"),
    ("windsurf", "Windsurf", "/static/icons/windsurf.png"),
    ("diving", "Bucear", "/static/icons/bucear.png"),
    ("family_day", "Pasar el día en familia", "/static/icons/familia_playa.png"),
    ("beach_sports", "Practicar deporte", "/static/icons/deporte_playa.png"),
]

BEACHES = [
    {
        "name": "Las Canteras",
        "municipality": "Las Palmas de Gran Canaria",
        "latitude": 28.1417,
        "longitude": -15.4300,
        "surface_type": "sand",
        "family_friendly": 1,
        "pet_friendly": 0,
        "food_nearby": 1,
        "has_surf_school": 1,
        "has_windsurf_school": 0,
        "has_sports_area": 1,
        "access_type": "easy",
        "default_air_temp_c": 24.0,
        "default_water_temp_c": 21.0,
        "default_wave_height_m": 0.8,
        "default_wind_kmh": 14.0,
        "default_cloud_cover_pct": 25.0,
        "default_rain_probability_pct": 10.0,
        "default_uv_index": 7.0,
    },
    {
        "name": "Maspalomas",
        "municipality": "San Bartolomé de Tirajana",
        "latitude": 27.7394,
        "longitude": -15.5845,
        "surface_type": "sand",
        "family_friendly": 1,
        "pet_friendly": 0,
        "food_nearby": 1,
        "has_surf_school": 0,
        "has_windsurf_school": 1,
        "has_sports_area": 1,
        "access_type": "easy",
        "default_air_temp_c": 25.0,
        "default_water_temp_c": 22.0,
        "default_wave_height_m": 1.1,
        "default_wind_kmh": 18.0,
        "default_cloud_cover_pct": 20.0,
        "default_rain_probability_pct": 8.0,
        "default_uv_index": 8.0,
    },
    {
        "name": "Vargas",
        "municipality": "Agüimes",
        "latitude": 27.9365,
        "longitude": -15.3897,
        "surface_type": "mixed",
        "family_friendly": 0,
        "pet_friendly": 0,
        "food_nearby": 0,
        "has_surf_school": 0,
        "has_windsurf_school": 1,
        "has_sports_area": 0,
        "access_type": "medium",
        "default_air_temp_c": 23.0,
        "default_water_temp_c": 21.0,
        "default_wave_height_m": 1.6,
        "default_wind_kmh": 28.0,
        "default_cloud_cover_pct": 30.0,
        "default_rain_probability_pct": 12.0,
        "default_uv_index": 7.0,
    },
    {
        "name": "Sardina del Norte",
        "municipality": "Gáldar",
        "latitude": 28.1650,
        "longitude": -15.6977,
        "surface_type": "mixed",
        "family_friendly": 0,
        "pet_friendly": 0,
        "food_nearby": 1,
        "has_surf_school": 0,
        "has_windsurf_school": 0,
        "has_sports_area": 0,
        "access_type": "medium",
        "default_air_temp_c": 23.0,
        "default_water_temp_c": 22.0,
        "default_wave_height_m": 0.9,
        "default_wind_kmh": 15.0,
        "default_cloud_cover_pct": 28.0,
        "default_rain_probability_pct": 10.0,
        "default_uv_index": 7.0,
    },
    {
        "name": "Amadores",
        "municipality": "Mogán",
        "latitude": 27.7878,
        "longitude": -15.7306,
        "surface_type": "sand",
        "family_friendly": 1,
        "pet_friendly": 0,
        "food_nearby": 1,
        "has_surf_school": 0,
        "has_windsurf_school": 0,
        "has_sports_area": 0,
        "access_type": "easy",
        "default_air_temp_c": 25.0,
        "default_water_temp_c": 22.0,
        "default_wave_height_m": 0.5,
        "default_wind_kmh": 10.0,
        "default_cloud_cover_pct": 18.0,
        "default_rain_probability_pct": 6.0,
        "default_uv_index": 8.0,
    },
    {
        "name": "El Confital",
        "municipality": "Las Palmas de Gran Canaria",
        "latitude": 28.1597,
        "longitude": -15.4460,
        "surface_type": "stone",
        "family_friendly": 0,
        "pet_friendly": 0,
        "food_nearby": 0,
        "has_surf_school": 1,
        "has_windsurf_school": 0,
        "has_sports_area": 0,
        "access_type": "medium",
        "default_air_temp_c": 24.0,
        "default_water_temp_c": 21.0,
        "default_wave_height_m": 1.8,
        "default_wind_kmh": 20.0,
        "default_cloud_cover_pct": 26.0,
        "default_rain_probability_pct": 10.0,
        "default_uv_index": 7.0,
    },
]

BEACH_ACTIVITY_COMPATIBILITY = [
    # beach_id will be resolved by name after insertion
    ("Las Canteras", "sunbathing", 0.90),
    ("Las Canteras", "surf", 0.65),
    ("Las Canteras", "windsurf", 0.40),
    ("Las Canteras", "diving", 0.55),
    ("Las Canteras", "family_day", 0.95),
    ("Las Canteras", "beach_sports", 0.90),

    ("Maspalomas", "sunbathing", 0.95),
    ("Maspalomas", "surf", 0.50),
    ("Maspalomas", "windsurf", 0.80),
    ("Maspalomas", "diving", 0.45),
    ("Maspalomas", "family_day", 0.90),
    ("Maspalomas", "beach_sports", 0.88),

    ("Vargas", "sunbathing", 0.35),
    ("Vargas", "surf", 0.78),
    ("Vargas", "windsurf", 0.98),
    ("Vargas", "diving", 0.40),
    ("Vargas", "family_day", 0.20),
    ("Vargas", "beach_sports", 0.45),

    ("Sardina del Norte", "sunbathing", 0.55),
    ("Sardina del Norte", "surf", 0.30),
    ("Sardina del Norte", "windsurf", 0.25),
    ("Sardina del Norte", "diving", 0.95),
    ("Sardina del Norte", "family_day", 0.35),
    ("Sardina del Norte", "beach_sports", 0.40),

    ("Amadores", "sunbathing", 0.96),
    ("Amadores", "surf", 0.15),
    ("Amadores", "windsurf", 0.20),
    ("Amadores", "diving", 0.65),
    ("Amadores", "family_day", 0.98),
    ("Amadores", "beach_sports", 0.60),

    ("El Confital", "sunbathing", 0.25),
    ("El Confital", "surf", 0.96),
    ("El Confital", "windsurf", 0.50),
    ("El Confital", "diving", 0.25),
    ("El Confital", "family_day", 0.10),
    ("El Confital", "beach_sports", 0.30),
]
