from .api import router as api_router
from .views import router as views_router
from .auth import router as auth_router
from .users import router as users_router
from .services import router as services_router
from .activities import router as activities_router
from .beaches import router as beaches_router
from .variables import router as variables_router
from .beach_conditions import router as beach_conditions_router
from .favorites import router as favourites_router
from .alerts import router as alerts_router
from .admin import router as admin_router
from .reviews import router as reviews_router
from .review_photo import router as review_photo_router
