from backend.models.activity import Activity
from backend.models.beach_condition import BeachCondition
from backend.models.beach_service import BeachService
from backend.models.beach import Beach
from backend.models.activity_variable_weight import ActivityVariableWeight
from backend.models.service import Service
from backend.models.user_activity_preference import UserActivityPreference
from backend.models.user_favorite_beaches import UserFavoriteBeaches
from backend.models.user import User
from backend.models.variable import Variable
