from backend.models.activity import Activity
from backend.models.beach_activity import BeachActivity
from backend.models.beach_condition import BeachCondition
from backend.models.beach_service import BeachService
from backend.models.beach import Beach
from backend.models.default_activity_weight import DefaultActivityWeight
from backend.models.service import Service
from backend.models.user_activity_preference import UserActivityPreference
from backend.models.user_favourite_beaches import UserFavoriteBeaches
from backend.models.user import User
